'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3655
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
 Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("dsMSR00019"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class dsMSR00019
    Inherits Global.System.Data.DataSet
    
    Private tableMSR00019Rpt As MSR00019RptDataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("MSR00019Rpt")) Is Nothing) Then
                MyBase.Tables.Add(New MSR00019RptDataTable(ds.Tables("MSR00019Rpt")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property MSR00019Rpt() As MSR00019RptDataTable
        Get
            Return Me.tableMSR00019Rpt
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As dsMSR00019 = CType(MyBase.Clone,dsMSR00019)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXml(reader)
            If (Not (ds.Tables("MSR00019Rpt")) Is Nothing) Then
                MyBase.Tables.Add(New MSR00019RptDataTable(ds.Tables("MSR00019Rpt")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tableMSR00019Rpt = CType(MyBase.Tables("MSR00019Rpt"),MSR00019RptDataTable)
        If (initTable = true) Then
            If (Not (Me.tableMSR00019Rpt) Is Nothing) Then
                Me.tableMSR00019Rpt.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub InitClass()
        Me.DataSetName = "dsMSR00019"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/DataSet12.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tableMSR00019Rpt = New MSR00019RptDataTable
        MyBase.Tables.Add(Me.tableMSR00019Rpt)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Function ShouldSerializeMSR00019Rpt() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As dsMSR00019 = New dsMSR00019
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    Public Delegate Sub MSR00019RptRowChangeEventHandler(ByVal sender As Object, ByVal e As MSR00019RptRowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
     Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class MSR00019RptDataTable
        Inherits Global.System.Data.DataTable
        Implements Global.System.Collections.IEnumerable
        
        Private columncocde As Global.System.Data.DataColumn
        
        Private columnSCfrom As Global.System.Data.DataColumn
        
        Private columnSCto As Global.System.Data.DataColumn
        
        Private columnDateFrom As Global.System.Data.DataColumn
        
        Private columnDateTo As Global.System.Data.DataColumn
        
        Private columnPCCfrom As Global.System.Data.DataColumn
        
        Private columnPCCto As Global.System.Data.DataColumn
        
        Private columnPCC2from As Global.System.Data.DataColumn
        
        Private columnPCC2to As Global.System.Data.DataColumn
        
        Private columnShpfrom As Global.System.Data.DataColumn
        
        Private columnShpto As Global.System.Data.DataColumn
        
        Private columnScstatus As Global.System.Data.DataColumn
        
        Private columnSort As Global.System.Data.DataColumn
        
        Private columnPayTrm As Global.System.Data.DataColumn
        
        Private columnPrintAmt As Global.System.Data.DataColumn
        
        Private columnsoh_verno As Global.System.Data.DataColumn
        
        Private columnsoh_ordsts As Global.System.Data.DataColumn
        
        Private columnsoh_ordno As Global.System.Data.DataColumn
        
        Private columnsoh_cuspo As Global.System.Data.DataColumn
        
        Private columnsoh_issdat As Global.System.Data.DataColumn
        
        Private columnsoh_shpstr As Global.System.Data.DataColumn
        
        Private columnsoh_shpend As Global.System.Data.DataColumn
        
        Private columnsoh_curcde As Global.System.Data.DataColumn
        
        Private columnsoh_ttlamt As Global.System.Data.DataColumn
        
        Private columnsoh_netamt As Global.System.Data.DataColumn
        
        Private columnPriCustNo As Global.System.Data.DataColumn
        
        Private columnPriCustShort As Global.System.Data.DataColumn
        
        Private columnSecCustNo As Global.System.Data.DataColumn
        
        Private columnSecCustShort As Global.System.Data.DataColumn
        
        Private columnPayTerm As Global.System.Data.DataColumn
        
        Private columnssm_imgnamM As Global.System.Data.DataColumn
        
        Private columnssm_imgnamS As Global.System.Data.DataColumn
        
        Private columnssm_imgnamI As Global.System.Data.DataColumn
        
        Private columncompName As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "MSR00019Rpt"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property cocdeColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columncocde
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property SCfromColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSCfrom
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property SCtoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSCto
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DateFromColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDateFrom
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property DateToColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnDateTo
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PCCfromColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPCCfrom
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PCCtoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPCCto
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PCC2fromColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPCC2from
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PCC2toColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPCC2to
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ShpfromColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnShpfrom
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ShptoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnShpto
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ScstatusColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnScstatus
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property SortColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSort
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PayTrmColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPayTrm
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PrintAmtColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPrintAmt
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property soh_vernoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnsoh_verno
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property soh_ordstsColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnsoh_ordsts
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property soh_ordnoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnsoh_ordno
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property soh_cuspoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnsoh_cuspo
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property soh_issdatColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnsoh_issdat
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property soh_shpstrColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnsoh_shpstr
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property soh_shpendColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnsoh_shpend
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property soh_curcdeColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnsoh_curcde
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property soh_ttlamtColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnsoh_ttlamt
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property soh_netamtColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnsoh_netamt
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PriCustNoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPriCustNo
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PriCustShortColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPriCustShort
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property SecCustNoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSecCustNo
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property SecCustShortColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnSecCustShort
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property PayTermColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnPayTerm
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ssm_imgnamMColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnssm_imgnamM
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ssm_imgnamSColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnssm_imgnamS
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ssm_imgnamIColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnssm_imgnamI
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property compNameColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columncompName
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As MSR00019RptRow
            Get
                Return CType(Me.Rows(index),MSR00019RptRow)
            End Get
        End Property
        
        Public Event MSR00019RptRowChanging As MSR00019RptRowChangeEventHandler
        
        Public Event MSR00019RptRowChanged As MSR00019RptRowChangeEventHandler
        
        Public Event MSR00019RptRowDeleting As MSR00019RptRowChangeEventHandler
        
        Public Event MSR00019RptRowDeleted As MSR00019RptRowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Sub AddMSR00019RptRow(ByVal row As MSR00019RptRow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Function AddMSR00019RptRow( _
                    ByVal cocde As String,  _
                    ByVal SCfrom As String,  _
                    ByVal SCto As String,  _
                    ByVal DateFrom As String,  _
                    ByVal DateTo As String,  _
                    ByVal PCCfrom As String,  _
                    ByVal PCCto As String,  _
                    ByVal PCC2from As String,  _
                    ByVal PCC2to As String,  _
                    ByVal Shpfrom As String,  _
                    ByVal Shpto As String,  _
                    ByVal Scstatus As String,  _
                    ByVal Sort As String,  _
                    ByVal PayTrm As String,  _
                    ByVal PrintAmt As String,  _
                    ByVal soh_verno As String,  _
                    ByVal soh_ordsts As String,  _
                    ByVal soh_ordno As String,  _
                    ByVal soh_cuspo As String,  _
                    ByVal soh_issdat As String,  _
                    ByVal soh_shpstr As String,  _
                    ByVal soh_shpend As String,  _
                    ByVal soh_curcde As String,  _
                    ByVal soh_ttlamt As Double,  _
                    ByVal soh_netamt As String,  _
                    ByVal PriCustNo As String,  _
                    ByVal PriCustShort As String,  _
                    ByVal SecCustNo As String,  _
                    ByVal SecCustShort As String,  _
                    ByVal PayTerm As String,  _
                    ByVal ssm_imgnamM As String,  _
                    ByVal ssm_imgnamS As String,  _
                    ByVal ssm_imgnamI As String,  _
                    ByVal compName As String) As MSR00019RptRow
            Dim rowMSR00019RptRow As MSR00019RptRow = CType(Me.NewRow,MSR00019RptRow)
            Dim columnValuesArray() As Object = New Object() {cocde, SCfrom, SCto, DateFrom, DateTo, PCCfrom, PCCto, PCC2from, PCC2to, Shpfrom, Shpto, Scstatus, Sort, PayTrm, PrintAmt, soh_verno, soh_ordsts, soh_ordno, soh_cuspo, soh_issdat, soh_shpstr, soh_shpend, soh_curcde, soh_ttlamt, soh_netamt, PriCustNo, PriCustShort, SecCustNo, SecCustShort, PayTerm, ssm_imgnamM, ssm_imgnamS, ssm_imgnamI, compName}
            rowMSR00019RptRow.ItemArray = columnValuesArray
            Me.Rows.Add(rowMSR00019RptRow)
            Return rowMSR00019RptRow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overridable Function GetEnumerator() As Global.System.Collections.IEnumerator Implements Global.System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As MSR00019RptDataTable = CType(MyBase.Clone,MSR00019RptDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New MSR00019RptDataTable
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub InitVars()
            Me.columncocde = MyBase.Columns("cocde")
            Me.columnSCfrom = MyBase.Columns("SCfrom")
            Me.columnSCto = MyBase.Columns("SCto")
            Me.columnDateFrom = MyBase.Columns("DateFrom")
            Me.columnDateTo = MyBase.Columns("DateTo")
            Me.columnPCCfrom = MyBase.Columns("PCCfrom")
            Me.columnPCCto = MyBase.Columns("PCCto")
            Me.columnPCC2from = MyBase.Columns("PCC2from")
            Me.columnPCC2to = MyBase.Columns("PCC2to")
            Me.columnShpfrom = MyBase.Columns("Shpfrom")
            Me.columnShpto = MyBase.Columns("Shpto")
            Me.columnScstatus = MyBase.Columns("Scstatus")
            Me.columnSort = MyBase.Columns("Sort")
            Me.columnPayTrm = MyBase.Columns("PayTrm")
            Me.columnPrintAmt = MyBase.Columns("PrintAmt")
            Me.columnsoh_verno = MyBase.Columns("soh_verno")
            Me.columnsoh_ordsts = MyBase.Columns("soh_ordsts")
            Me.columnsoh_ordno = MyBase.Columns("soh_ordno")
            Me.columnsoh_cuspo = MyBase.Columns("soh_cuspo")
            Me.columnsoh_issdat = MyBase.Columns("soh_issdat")
            Me.columnsoh_shpstr = MyBase.Columns("soh_shpstr")
            Me.columnsoh_shpend = MyBase.Columns("soh_shpend")
            Me.columnsoh_curcde = MyBase.Columns("soh_curcde")
            Me.columnsoh_ttlamt = MyBase.Columns("soh_ttlamt")
            Me.columnsoh_netamt = MyBase.Columns("soh_netamt")
            Me.columnPriCustNo = MyBase.Columns("PriCustNo")
            Me.columnPriCustShort = MyBase.Columns("PriCustShort")
            Me.columnSecCustNo = MyBase.Columns("SecCustNo")
            Me.columnSecCustShort = MyBase.Columns("SecCustShort")
            Me.columnPayTerm = MyBase.Columns("PayTerm")
            Me.columnssm_imgnamM = MyBase.Columns("ssm_imgnamM")
            Me.columnssm_imgnamS = MyBase.Columns("ssm_imgnamS")
            Me.columnssm_imgnamI = MyBase.Columns("ssm_imgnamI")
            Me.columncompName = MyBase.Columns("compName")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitClass()
            Me.columncocde = New Global.System.Data.DataColumn("cocde", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columncocde)
            Me.columnSCfrom = New Global.System.Data.DataColumn("SCfrom", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSCfrom)
            Me.columnSCto = New Global.System.Data.DataColumn("SCto", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSCto)
            Me.columnDateFrom = New Global.System.Data.DataColumn("DateFrom", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDateFrom)
            Me.columnDateTo = New Global.System.Data.DataColumn("DateTo", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnDateTo)
            Me.columnPCCfrom = New Global.System.Data.DataColumn("PCCfrom", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPCCfrom)
            Me.columnPCCto = New Global.System.Data.DataColumn("PCCto", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPCCto)
            Me.columnPCC2from = New Global.System.Data.DataColumn("PCC2from", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPCC2from)
            Me.columnPCC2to = New Global.System.Data.DataColumn("PCC2to", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPCC2to)
            Me.columnShpfrom = New Global.System.Data.DataColumn("Shpfrom", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnShpfrom)
            Me.columnShpto = New Global.System.Data.DataColumn("Shpto", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnShpto)
            Me.columnScstatus = New Global.System.Data.DataColumn("Scstatus", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnScstatus)
            Me.columnSort = New Global.System.Data.DataColumn("Sort", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSort)
            Me.columnPayTrm = New Global.System.Data.DataColumn("PayTrm", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPayTrm)
            Me.columnPrintAmt = New Global.System.Data.DataColumn("PrintAmt", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPrintAmt)
            Me.columnsoh_verno = New Global.System.Data.DataColumn("soh_verno", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnsoh_verno)
            Me.columnsoh_ordsts = New Global.System.Data.DataColumn("soh_ordsts", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnsoh_ordsts)
            Me.columnsoh_ordno = New Global.System.Data.DataColumn("soh_ordno", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnsoh_ordno)
            Me.columnsoh_cuspo = New Global.System.Data.DataColumn("soh_cuspo", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnsoh_cuspo)
            Me.columnsoh_issdat = New Global.System.Data.DataColumn("soh_issdat", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnsoh_issdat)
            Me.columnsoh_shpstr = New Global.System.Data.DataColumn("soh_shpstr", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnsoh_shpstr)
            Me.columnsoh_shpend = New Global.System.Data.DataColumn("soh_shpend", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnsoh_shpend)
            Me.columnsoh_curcde = New Global.System.Data.DataColumn("soh_curcde", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnsoh_curcde)
            Me.columnsoh_ttlamt = New Global.System.Data.DataColumn("soh_ttlamt", GetType(Double), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnsoh_ttlamt)
            Me.columnsoh_netamt = New Global.System.Data.DataColumn("soh_netamt", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnsoh_netamt)
            Me.columnPriCustNo = New Global.System.Data.DataColumn("PriCustNo", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPriCustNo)
            Me.columnPriCustShort = New Global.System.Data.DataColumn("PriCustShort", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPriCustShort)
            Me.columnSecCustNo = New Global.System.Data.DataColumn("SecCustNo", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSecCustNo)
            Me.columnSecCustShort = New Global.System.Data.DataColumn("SecCustShort", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnSecCustShort)
            Me.columnPayTerm = New Global.System.Data.DataColumn("PayTerm", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnPayTerm)
            Me.columnssm_imgnamM = New Global.System.Data.DataColumn("ssm_imgnamM", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnssm_imgnamM)
            Me.columnssm_imgnamS = New Global.System.Data.DataColumn("ssm_imgnamS", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnssm_imgnamS)
            Me.columnssm_imgnamI = New Global.System.Data.DataColumn("ssm_imgnamI", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnssm_imgnamI)
            Me.columncompName = New Global.System.Data.DataColumn("compName", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columncompName)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function NewMSR00019RptRow() As MSR00019RptRow
            Return CType(Me.NewRow,MSR00019RptRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New MSR00019RptRow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(MSR00019RptRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.MSR00019RptRowChangedEvent) Is Nothing) Then
                RaiseEvent MSR00019RptRowChanged(Me, New MSR00019RptRowChangeEvent(CType(e.Row,MSR00019RptRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.MSR00019RptRowChangingEvent) Is Nothing) Then
                RaiseEvent MSR00019RptRowChanging(Me, New MSR00019RptRowChangeEvent(CType(e.Row,MSR00019RptRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.MSR00019RptRowDeletedEvent) Is Nothing) Then
                RaiseEvent MSR00019RptRowDeleted(Me, New MSR00019RptRowChangeEvent(CType(e.Row,MSR00019RptRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.MSR00019RptRowDeletingEvent) Is Nothing) Then
                RaiseEvent MSR00019RptRowDeleting(Me, New MSR00019RptRowChangeEvent(CType(e.Row,MSR00019RptRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub RemoveMSR00019RptRow(ByVal row As MSR00019RptRow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
            Dim ds As dsMSR00019 = New dsMSR00019
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "MSR00019RptDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Partial Public Class MSR00019RptRow
        Inherits Global.System.Data.DataRow
        
        Private tableMSR00019Rpt As MSR00019RptDataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tableMSR00019Rpt = CType(Me.Table,MSR00019RptDataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property cocde() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.cocdeColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'cocde' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.cocdeColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SCfrom() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.SCfromColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SCfrom' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.SCfromColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SCto() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.SCtoColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SCto' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.SCtoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DateFrom() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.DateFromColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DateFrom' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.DateFromColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property DateTo() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.DateToColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'DateTo' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.DateToColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PCCfrom() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.PCCfromColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PCCfrom' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.PCCfromColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PCCto() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.PCCtoColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PCCto' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.PCCtoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PCC2from() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.PCC2fromColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PCC2from' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.PCC2fromColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PCC2to() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.PCC2toColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PCC2to' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.PCC2toColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Shpfrom() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.ShpfromColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Shpfrom' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.ShpfromColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Shpto() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.ShptoColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Shpto' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.ShptoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Scstatus() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.ScstatusColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Scstatus' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.ScstatusColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Sort() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.SortColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Sort' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.SortColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PayTrm() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.PayTrmColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PayTrm' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.PayTrmColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PrintAmt() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.PrintAmtColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PrintAmt' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.PrintAmtColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property soh_verno() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.soh_vernoColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'soh_verno' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.soh_vernoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property soh_ordsts() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.soh_ordstsColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'soh_ordsts' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.soh_ordstsColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property soh_ordno() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.soh_ordnoColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'soh_ordno' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.soh_ordnoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property soh_cuspo() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.soh_cuspoColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'soh_cuspo' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.soh_cuspoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property soh_issdat() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.soh_issdatColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'soh_issdat' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.soh_issdatColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property soh_shpstr() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.soh_shpstrColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'soh_shpstr' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.soh_shpstrColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property soh_shpend() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.soh_shpendColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'soh_shpend' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.soh_shpendColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property soh_curcde() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.soh_curcdeColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'soh_curcde' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.soh_curcdeColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property soh_ttlamt() As Double
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.soh_ttlamtColumn),Double)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'soh_ttlamt' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.soh_ttlamtColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property soh_netamt() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.soh_netamtColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'soh_netamt' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.soh_netamtColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PriCustNo() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.PriCustNoColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PriCustNo' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.PriCustNoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PriCustShort() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.PriCustShortColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PriCustShort' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.PriCustShortColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SecCustNo() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.SecCustNoColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SecCustNo' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.SecCustNoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property SecCustShort() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.SecCustShortColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'SecCustShort' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.SecCustShortColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property PayTerm() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.PayTermColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'PayTerm' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.PayTermColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ssm_imgnamM() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.ssm_imgnamMColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ssm_imgnamM' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.ssm_imgnamMColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ssm_imgnamS() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.ssm_imgnamSColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ssm_imgnamS' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.ssm_imgnamSColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ssm_imgnamI() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.ssm_imgnamIColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ssm_imgnamI' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.ssm_imgnamIColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property compName() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR00019Rpt.compNameColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'compName' in table 'MSR00019Rpt' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR00019Rpt.compNameColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IscocdeNull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.cocdeColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetcocdeNull()
            Me(Me.tableMSR00019Rpt.cocdeColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSCfromNull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.SCfromColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSCfromNull()
            Me(Me.tableMSR00019Rpt.SCfromColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSCtoNull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.SCtoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSCtoNull()
            Me(Me.tableMSR00019Rpt.SCtoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDateFromNull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.DateFromColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDateFromNull()
            Me(Me.tableMSR00019Rpt.DateFromColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsDateToNull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.DateToColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetDateToNull()
            Me(Me.tableMSR00019Rpt.DateToColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPCCfromNull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.PCCfromColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPCCfromNull()
            Me(Me.tableMSR00019Rpt.PCCfromColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPCCtoNull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.PCCtoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPCCtoNull()
            Me(Me.tableMSR00019Rpt.PCCtoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPCC2fromNull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.PCC2fromColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPCC2fromNull()
            Me(Me.tableMSR00019Rpt.PCC2fromColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPCC2toNull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.PCC2toColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPCC2toNull()
            Me(Me.tableMSR00019Rpt.PCC2toColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsShpfromNull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.ShpfromColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetShpfromNull()
            Me(Me.tableMSR00019Rpt.ShpfromColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsShptoNull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.ShptoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetShptoNull()
            Me(Me.tableMSR00019Rpt.ShptoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsScstatusNull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.ScstatusColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetScstatusNull()
            Me(Me.tableMSR00019Rpt.ScstatusColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSortNull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.SortColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSortNull()
            Me(Me.tableMSR00019Rpt.SortColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPayTrmNull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.PayTrmColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPayTrmNull()
            Me(Me.tableMSR00019Rpt.PayTrmColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPrintAmtNull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.PrintAmtColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPrintAmtNull()
            Me(Me.tableMSR00019Rpt.PrintAmtColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Issoh_vernoNull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.soh_vernoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setsoh_vernoNull()
            Me(Me.tableMSR00019Rpt.soh_vernoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Issoh_ordstsNull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.soh_ordstsColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setsoh_ordstsNull()
            Me(Me.tableMSR00019Rpt.soh_ordstsColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Issoh_ordnoNull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.soh_ordnoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setsoh_ordnoNull()
            Me(Me.tableMSR00019Rpt.soh_ordnoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Issoh_cuspoNull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.soh_cuspoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setsoh_cuspoNull()
            Me(Me.tableMSR00019Rpt.soh_cuspoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Issoh_issdatNull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.soh_issdatColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setsoh_issdatNull()
            Me(Me.tableMSR00019Rpt.soh_issdatColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Issoh_shpstrNull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.soh_shpstrColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setsoh_shpstrNull()
            Me(Me.tableMSR00019Rpt.soh_shpstrColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Issoh_shpendNull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.soh_shpendColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setsoh_shpendNull()
            Me(Me.tableMSR00019Rpt.soh_shpendColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Issoh_curcdeNull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.soh_curcdeColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setsoh_curcdeNull()
            Me(Me.tableMSR00019Rpt.soh_curcdeColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Issoh_ttlamtNull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.soh_ttlamtColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setsoh_ttlamtNull()
            Me(Me.tableMSR00019Rpt.soh_ttlamtColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Issoh_netamtNull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.soh_netamtColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setsoh_netamtNull()
            Me(Me.tableMSR00019Rpt.soh_netamtColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPriCustNoNull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.PriCustNoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPriCustNoNull()
            Me(Me.tableMSR00019Rpt.PriCustNoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPriCustShortNull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.PriCustShortColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPriCustShortNull()
            Me(Me.tableMSR00019Rpt.PriCustShortColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSecCustNoNull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.SecCustNoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSecCustNoNull()
            Me(Me.tableMSR00019Rpt.SecCustNoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsSecCustShortNull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.SecCustShortColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetSecCustShortNull()
            Me(Me.tableMSR00019Rpt.SecCustShortColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsPayTermNull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.PayTermColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetPayTermNull()
            Me(Me.tableMSR00019Rpt.PayTermColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isssm_imgnamMNull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.ssm_imgnamMColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setssm_imgnamMNull()
            Me(Me.tableMSR00019Rpt.ssm_imgnamMColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isssm_imgnamSNull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.ssm_imgnamSColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setssm_imgnamSNull()
            Me(Me.tableMSR00019Rpt.ssm_imgnamSColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isssm_imgnamINull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.ssm_imgnamIColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setssm_imgnamINull()
            Me(Me.tableMSR00019Rpt.ssm_imgnamIColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IscompNameNull() As Boolean
            Return Me.IsNull(Me.tableMSR00019Rpt.compNameColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetcompNameNull()
            Me(Me.tableMSR00019Rpt.compNameColumn) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Public Class MSR00019RptRowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As MSR00019RptRow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New(ByVal row As MSR00019RptRow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Row() As MSR00019RptRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
