'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3655
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
 Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("DataSet1"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class DataSet1
    Inherits Global.System.Data.DataSet
    
    Private tablempr00002 As mpr00002DataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("mpr00002")) Is Nothing) Then
                MyBase.Tables.Add(New mpr00002DataTable(ds.Tables("mpr00002")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property mpr00002() As mpr00002DataTable
        Get
            Return Me.tablempr00002
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As DataSet1 = CType(MyBase.Clone,DataSet1)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXml(reader)
            If (Not (ds.Tables("mpr00002")) Is Nothing) Then
                MyBase.Tables.Add(New mpr00002DataTable(ds.Tables("mpr00002")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tablempr00002 = CType(MyBase.Tables("mpr00002"),mpr00002DataTable)
        If (initTable = true) Then
            If (Not (Me.tablempr00002) Is Nothing) Then
                Me.tablempr00002.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub InitClass()
        Me.DataSetName = "DataSet1"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/DataSet1.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tablempr00002 = New mpr00002DataTable
        MyBase.Tables.Add(Me.tablempr00002)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Function ShouldSerializempr00002() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As DataSet1 = New DataSet1
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    Public Delegate Sub mpr00002RowChangeEventHandler(ByVal sender As Object, ByVal e As mpr00002RowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
     Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class mpr00002DataTable
        Inherits Global.System.Data.DataTable
        Implements Global.System.Collections.IEnumerable
        
        Private columnMph_MPONO As Global.System.Data.DataColumn
        
        Private columnMph_VenNo As Global.System.Data.DataColumn
        
        Private columnvbi_vennam As Global.System.Data.DataColumn
        
        Private columnMph_ImpFty As Global.System.Data.DataColumn
        
        Private columnGvi_VenNam As Global.System.Data.DataColumn
        
        Private columnGvi_EngNam As Global.System.Data.DataColumn
        
        Private columnGvi_VenAddr As Global.System.Data.DataColumn
        
        Private columnGvi_EngAddr As Global.System.Data.DataColumn
        
        Private columnGvi_Tel1 As Global.System.Data.DataColumn
        
        Private columnGvi_Tel2 As Global.System.Data.DataColumn
        
        Private columnGvi_Fax As Global.System.Data.DataColumn
        
        Private columnGvi_TLX As Global.System.Data.DataColumn
        
        Private columnMph_Curr As Global.System.Data.DataColumn
        
        Private columnMph_ShpPlc As Global.System.Data.DataColumn
        
        Private columnMph_rmk As Global.System.Data.DataColumn
        
        Private columnMph_VenAdr As Global.System.Data.DataColumn
        
        Private columnMph_VenStt As Global.System.Data.DataColumn
        
        Private columnMph_VenCty As Global.System.Data.DataColumn
        
        Private columnysi_dsc As Global.System.Data.DataColumn
        
        Private columnMph_VenPst As Global.System.Data.DataColumn
        
        Private columnMph_MporCtp As Global.System.Data.DataColumn
        
        Private columnMph_DisCnt As Global.System.Data.DataColumn
        
        Private columnMph_ShpAdr As Global.System.Data.DataColumn
        
        Private columnMph_CreDat As Global.System.Data.DataColumn
        
        Private columnMph_UpdDat As Global.System.Data.DataColumn
        
        Private columnMpd_ItmNo As Global.System.Data.DataColumn
        
        Private columnMpd_VenItm As Global.System.Data.DataColumn
        
        Private columnMpd_ItmNam As Global.System.Data.DataColumn
        
        Private columnMpd_UM As Global.System.Data.DataColumn
        
        Private columndetailinfo As Global.System.Data.DataColumn
        
        Private columnMPD_QTY As Global.System.Data.DataColumn
        
        Private columnMpd_MinPrc As Global.System.Data.DataColumn
        
        Private columnmpd_subamt As Global.System.Data.DataColumn
        
        Private columnMpd_ShpDat As Global.System.Data.DataColumn
        
        Private columnRevised_Flag As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "mpr00002"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Mph_MPONOColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMph_MPONO
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Mph_VenNoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMph_VenNo
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property vbi_vennamColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnvbi_vennam
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Mph_ImpFtyColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMph_ImpFty
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Gvi_VenNamColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnGvi_VenNam
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Gvi_EngNamColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnGvi_EngNam
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Gvi_VenAddrColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnGvi_VenAddr
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Gvi_EngAddrColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnGvi_EngAddr
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Gvi_Tel1Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnGvi_Tel1
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Gvi_Tel2Column() As Global.System.Data.DataColumn
            Get
                Return Me.columnGvi_Tel2
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Gvi_FaxColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnGvi_Fax
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Gvi_TLXColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnGvi_TLX
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Mph_CurrColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMph_Curr
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Mph_ShpPlcColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMph_ShpPlc
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Mph_rmkColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMph_rmk
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Mph_VenAdrColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMph_VenAdr
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Mph_VenSttColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMph_VenStt
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Mph_VenCtyColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMph_VenCty
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property ysi_dscColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnysi_dsc
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Mph_VenPstColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMph_VenPst
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Mph_MporCtpColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMph_MporCtp
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Mph_DisCntColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMph_DisCnt
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Mph_ShpAdrColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMph_ShpAdr
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Mph_CreDatColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMph_CreDat
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Mph_UpdDatColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMph_UpdDat
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Mpd_ItmNoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMpd_ItmNo
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Mpd_VenItmColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMpd_VenItm
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Mpd_ItmNamColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMpd_ItmNam
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Mpd_UMColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMpd_UM
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property detailinfoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columndetailinfo
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property MPD_QTYColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMPD_QTY
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Mpd_MinPrcColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMpd_MinPrc
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property mpd_subamtColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnmpd_subamt
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Mpd_ShpDatColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnMpd_ShpDat
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Revised_FlagColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnRevised_Flag
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As mpr00002Row
            Get
                Return CType(Me.Rows(index),mpr00002Row)
            End Get
        End Property
        
        Public Event mpr00002RowChanging As mpr00002RowChangeEventHandler
        
        Public Event mpr00002RowChanged As mpr00002RowChangeEventHandler
        
        Public Event mpr00002RowDeleting As mpr00002RowChangeEventHandler
        
        Public Event mpr00002RowDeleted As mpr00002RowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Sub Addmpr00002Row(ByVal row As mpr00002Row)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Function Addmpr00002Row( _
                    ByVal Mph_MPONO As String,  _
                    ByVal Mph_VenNo As String,  _
                    ByVal vbi_vennam As String,  _
                    ByVal Mph_ImpFty As String,  _
                    ByVal Gvi_VenNam As String,  _
                    ByVal Gvi_EngNam As String,  _
                    ByVal Gvi_VenAddr As String,  _
                    ByVal Gvi_EngAddr As String,  _
                    ByVal Gvi_Tel1 As String,  _
                    ByVal Gvi_Tel2 As String,  _
                    ByVal Gvi_Fax As String,  _
                    ByVal Gvi_TLX As String,  _
                    ByVal Mph_Curr As String,  _
                    ByVal Mph_ShpPlc As String,  _
                    ByVal Mph_rmk As String,  _
                    ByVal Mph_VenAdr As String,  _
                    ByVal Mph_VenStt As String,  _
                    ByVal Mph_VenCty As String,  _
                    ByVal ysi_dsc As String,  _
                    ByVal Mph_VenPst As String,  _
                    ByVal Mph_MporCtp As String,  _
                    ByVal Mph_DisCnt As String,  _
                    ByVal Mph_ShpAdr As String,  _
                    ByVal Mph_CreDat As String,  _
                    ByVal Mph_UpdDat As String,  _
                    ByVal Mpd_ItmNo As String,  _
                    ByVal Mpd_VenItm As String,  _
                    ByVal Mpd_ItmNam As String,  _
                    ByVal Mpd_UM As String,  _
                    ByVal detailinfo As String,  _
                    ByVal MPD_QTY As String,  _
                    ByVal Mpd_MinPrc As String,  _
                    ByVal mpd_subamt As Double,  _
                    ByVal Mpd_ShpDat As String,  _
                    ByVal Revised_Flag As String) As mpr00002Row
            Dim rowmpr00002Row As mpr00002Row = CType(Me.NewRow,mpr00002Row)
            Dim columnValuesArray() As Object = New Object() {Mph_MPONO, Mph_VenNo, vbi_vennam, Mph_ImpFty, Gvi_VenNam, Gvi_EngNam, Gvi_VenAddr, Gvi_EngAddr, Gvi_Tel1, Gvi_Tel2, Gvi_Fax, Gvi_TLX, Mph_Curr, Mph_ShpPlc, Mph_rmk, Mph_VenAdr, Mph_VenStt, Mph_VenCty, ysi_dsc, Mph_VenPst, Mph_MporCtp, Mph_DisCnt, Mph_ShpAdr, Mph_CreDat, Mph_UpdDat, Mpd_ItmNo, Mpd_VenItm, Mpd_ItmNam, Mpd_UM, detailinfo, MPD_QTY, Mpd_MinPrc, mpd_subamt, Mpd_ShpDat, Revised_Flag}
            rowmpr00002Row.ItemArray = columnValuesArray
            Me.Rows.Add(rowmpr00002Row)
            Return rowmpr00002Row
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overridable Function GetEnumerator() As Global.System.Collections.IEnumerator Implements Global.System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As mpr00002DataTable = CType(MyBase.Clone,mpr00002DataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New mpr00002DataTable
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub InitVars()
            Me.columnMph_MPONO = MyBase.Columns("Mph_MPONO")
            Me.columnMph_VenNo = MyBase.Columns("Mph_VenNo")
            Me.columnvbi_vennam = MyBase.Columns("vbi_vennam")
            Me.columnMph_ImpFty = MyBase.Columns("Mph_ImpFty")
            Me.columnGvi_VenNam = MyBase.Columns("Gvi_VenNam")
            Me.columnGvi_EngNam = MyBase.Columns("Gvi_EngNam")
            Me.columnGvi_VenAddr = MyBase.Columns("Gvi_VenAddr")
            Me.columnGvi_EngAddr = MyBase.Columns("Gvi_EngAddr")
            Me.columnGvi_Tel1 = MyBase.Columns("Gvi_Tel1")
            Me.columnGvi_Tel2 = MyBase.Columns("Gvi_Tel2")
            Me.columnGvi_Fax = MyBase.Columns("Gvi_Fax")
            Me.columnGvi_TLX = MyBase.Columns("Gvi_TLX")
            Me.columnMph_Curr = MyBase.Columns("Mph_Curr")
            Me.columnMph_ShpPlc = MyBase.Columns("Mph_ShpPlc")
            Me.columnMph_rmk = MyBase.Columns("Mph_rmk")
            Me.columnMph_VenAdr = MyBase.Columns("Mph_VenAdr")
            Me.columnMph_VenStt = MyBase.Columns("Mph_VenStt")
            Me.columnMph_VenCty = MyBase.Columns("Mph_VenCty")
            Me.columnysi_dsc = MyBase.Columns("ysi_dsc")
            Me.columnMph_VenPst = MyBase.Columns("Mph_VenPst")
            Me.columnMph_MporCtp = MyBase.Columns("Mph_MporCtp")
            Me.columnMph_DisCnt = MyBase.Columns("Mph_DisCnt")
            Me.columnMph_ShpAdr = MyBase.Columns("Mph_ShpAdr")
            Me.columnMph_CreDat = MyBase.Columns("Mph_CreDat")
            Me.columnMph_UpdDat = MyBase.Columns("Mph_UpdDat")
            Me.columnMpd_ItmNo = MyBase.Columns("Mpd_ItmNo")
            Me.columnMpd_VenItm = MyBase.Columns("Mpd_VenItm")
            Me.columnMpd_ItmNam = MyBase.Columns("Mpd_ItmNam")
            Me.columnMpd_UM = MyBase.Columns("Mpd_UM")
            Me.columndetailinfo = MyBase.Columns("detailinfo")
            Me.columnMPD_QTY = MyBase.Columns("MPD_QTY")
            Me.columnMpd_MinPrc = MyBase.Columns("Mpd_MinPrc")
            Me.columnmpd_subamt = MyBase.Columns("mpd_subamt")
            Me.columnMpd_ShpDat = MyBase.Columns("Mpd_ShpDat")
            Me.columnRevised_Flag = MyBase.Columns("Revised_Flag")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitClass()
            Me.columnMph_MPONO = New Global.System.Data.DataColumn("Mph_MPONO", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMph_MPONO)
            Me.columnMph_VenNo = New Global.System.Data.DataColumn("Mph_VenNo", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMph_VenNo)
            Me.columnvbi_vennam = New Global.System.Data.DataColumn("vbi_vennam", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnvbi_vennam)
            Me.columnMph_ImpFty = New Global.System.Data.DataColumn("Mph_ImpFty", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMph_ImpFty)
            Me.columnGvi_VenNam = New Global.System.Data.DataColumn("Gvi_VenNam", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnGvi_VenNam)
            Me.columnGvi_EngNam = New Global.System.Data.DataColumn("Gvi_EngNam", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnGvi_EngNam)
            Me.columnGvi_VenAddr = New Global.System.Data.DataColumn("Gvi_VenAddr", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnGvi_VenAddr)
            Me.columnGvi_EngAddr = New Global.System.Data.DataColumn("Gvi_EngAddr", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnGvi_EngAddr)
            Me.columnGvi_Tel1 = New Global.System.Data.DataColumn("Gvi_Tel1", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnGvi_Tel1)
            Me.columnGvi_Tel2 = New Global.System.Data.DataColumn("Gvi_Tel2", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnGvi_Tel2)
            Me.columnGvi_Fax = New Global.System.Data.DataColumn("Gvi_Fax", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnGvi_Fax)
            Me.columnGvi_TLX = New Global.System.Data.DataColumn("Gvi_TLX", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnGvi_TLX)
            Me.columnMph_Curr = New Global.System.Data.DataColumn("Mph_Curr", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMph_Curr)
            Me.columnMph_ShpPlc = New Global.System.Data.DataColumn("Mph_ShpPlc", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMph_ShpPlc)
            Me.columnMph_rmk = New Global.System.Data.DataColumn("Mph_rmk", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMph_rmk)
            Me.columnMph_VenAdr = New Global.System.Data.DataColumn("Mph_VenAdr", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMph_VenAdr)
            Me.columnMph_VenStt = New Global.System.Data.DataColumn("Mph_VenStt", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMph_VenStt)
            Me.columnMph_VenCty = New Global.System.Data.DataColumn("Mph_VenCty", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMph_VenCty)
            Me.columnysi_dsc = New Global.System.Data.DataColumn("ysi_dsc", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnysi_dsc)
            Me.columnMph_VenPst = New Global.System.Data.DataColumn("Mph_VenPst", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMph_VenPst)
            Me.columnMph_MporCtp = New Global.System.Data.DataColumn("Mph_MporCtp", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMph_MporCtp)
            Me.columnMph_DisCnt = New Global.System.Data.DataColumn("Mph_DisCnt", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMph_DisCnt)
            Me.columnMph_ShpAdr = New Global.System.Data.DataColumn("Mph_ShpAdr", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMph_ShpAdr)
            Me.columnMph_CreDat = New Global.System.Data.DataColumn("Mph_CreDat", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMph_CreDat)
            Me.columnMph_UpdDat = New Global.System.Data.DataColumn("Mph_UpdDat", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMph_UpdDat)
            Me.columnMpd_ItmNo = New Global.System.Data.DataColumn("Mpd_ItmNo", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMpd_ItmNo)
            Me.columnMpd_VenItm = New Global.System.Data.DataColumn("Mpd_VenItm", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMpd_VenItm)
            Me.columnMpd_ItmNam = New Global.System.Data.DataColumn("Mpd_ItmNam", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMpd_ItmNam)
            Me.columnMpd_UM = New Global.System.Data.DataColumn("Mpd_UM", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMpd_UM)
            Me.columndetailinfo = New Global.System.Data.DataColumn("detailinfo", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columndetailinfo)
            Me.columnMPD_QTY = New Global.System.Data.DataColumn("MPD_QTY", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMPD_QTY)
            Me.columnMpd_MinPrc = New Global.System.Data.DataColumn("Mpd_MinPrc", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMpd_MinPrc)
            Me.columnmpd_subamt = New Global.System.Data.DataColumn("mpd_subamt", GetType(Double), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnmpd_subamt)
            Me.columnMpd_ShpDat = New Global.System.Data.DataColumn("Mpd_ShpDat", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnMpd_ShpDat)
            Me.columnRevised_Flag = New Global.System.Data.DataColumn("Revised_Flag", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnRevised_Flag)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Newmpr00002Row() As mpr00002Row
            Return CType(Me.NewRow,mpr00002Row)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New mpr00002Row(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(mpr00002Row)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.mpr00002RowChangedEvent) Is Nothing) Then
                RaiseEvent mpr00002RowChanged(Me, New mpr00002RowChangeEvent(CType(e.Row,mpr00002Row), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.mpr00002RowChangingEvent) Is Nothing) Then
                RaiseEvent mpr00002RowChanging(Me, New mpr00002RowChangeEvent(CType(e.Row,mpr00002Row), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.mpr00002RowDeletedEvent) Is Nothing) Then
                RaiseEvent mpr00002RowDeleted(Me, New mpr00002RowChangeEvent(CType(e.Row,mpr00002Row), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.mpr00002RowDeletingEvent) Is Nothing) Then
                RaiseEvent mpr00002RowDeleting(Me, New mpr00002RowChangeEvent(CType(e.Row,mpr00002Row), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Removempr00002Row(ByVal row As mpr00002Row)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
            Dim ds As DataSet1 = New DataSet1
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "mpr00002DataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Partial Public Class mpr00002Row
        Inherits Global.System.Data.DataRow
        
        Private tablempr00002 As mpr00002DataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tablempr00002 = CType(Me.Table,mpr00002DataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Mph_MPONO() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.Mph_MPONOColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Mph_MPONO' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.Mph_MPONOColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Mph_VenNo() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.Mph_VenNoColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Mph_VenNo' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.Mph_VenNoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property vbi_vennam() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.vbi_vennamColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'vbi_vennam' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.vbi_vennamColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Mph_ImpFty() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.Mph_ImpFtyColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Mph_ImpFty' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.Mph_ImpFtyColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Gvi_VenNam() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.Gvi_VenNamColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Gvi_VenNam' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.Gvi_VenNamColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Gvi_EngNam() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.Gvi_EngNamColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Gvi_EngNam' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.Gvi_EngNamColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Gvi_VenAddr() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.Gvi_VenAddrColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Gvi_VenAddr' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.Gvi_VenAddrColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Gvi_EngAddr() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.Gvi_EngAddrColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Gvi_EngAddr' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.Gvi_EngAddrColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Gvi_Tel1() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.Gvi_Tel1Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Gvi_Tel1' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.Gvi_Tel1Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Gvi_Tel2() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.Gvi_Tel2Column),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Gvi_Tel2' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.Gvi_Tel2Column) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Gvi_Fax() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.Gvi_FaxColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Gvi_Fax' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.Gvi_FaxColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Gvi_TLX() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.Gvi_TLXColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Gvi_TLX' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.Gvi_TLXColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Mph_Curr() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.Mph_CurrColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Mph_Curr' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.Mph_CurrColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Mph_ShpPlc() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.Mph_ShpPlcColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Mph_ShpPlc' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.Mph_ShpPlcColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Mph_rmk() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.Mph_rmkColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Mph_rmk' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.Mph_rmkColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Mph_VenAdr() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.Mph_VenAdrColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Mph_VenAdr' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.Mph_VenAdrColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Mph_VenStt() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.Mph_VenSttColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Mph_VenStt' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.Mph_VenSttColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Mph_VenCty() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.Mph_VenCtyColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Mph_VenCty' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.Mph_VenCtyColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property ysi_dsc() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.ysi_dscColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'ysi_dsc' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.ysi_dscColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Mph_VenPst() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.Mph_VenPstColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Mph_VenPst' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.Mph_VenPstColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Mph_MporCtp() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.Mph_MporCtpColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Mph_MporCtp' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.Mph_MporCtpColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Mph_DisCnt() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.Mph_DisCntColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Mph_DisCnt' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.Mph_DisCntColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Mph_ShpAdr() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.Mph_ShpAdrColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Mph_ShpAdr' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.Mph_ShpAdrColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Mph_CreDat() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.Mph_CreDatColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Mph_CreDat' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.Mph_CreDatColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Mph_UpdDat() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.Mph_UpdDatColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Mph_UpdDat' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.Mph_UpdDatColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Mpd_ItmNo() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.Mpd_ItmNoColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Mpd_ItmNo' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.Mpd_ItmNoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Mpd_VenItm() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.Mpd_VenItmColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Mpd_VenItm' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.Mpd_VenItmColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Mpd_ItmNam() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.Mpd_ItmNamColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Mpd_ItmNam' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.Mpd_ItmNamColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Mpd_UM() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.Mpd_UMColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Mpd_UM' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.Mpd_UMColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property detailinfo() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.detailinfoColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'detailinfo' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.detailinfoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property MPD_QTY() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.MPD_QTYColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'MPD_QTY' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.MPD_QTYColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Mpd_MinPrc() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.Mpd_MinPrcColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Mpd_MinPrc' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.Mpd_MinPrcColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property mpd_subamt() As Double
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.mpd_subamtColumn),Double)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'mpd_subamt' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.mpd_subamtColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Mpd_ShpDat() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.Mpd_ShpDatColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Mpd_ShpDat' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.Mpd_ShpDatColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Revised_Flag() As String
            Get
                Try 
                    Return CType(Me(Me.tablempr00002.Revised_FlagColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Revised_Flag' in table 'mpr00002' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tablempr00002.Revised_FlagColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMph_MPONONull() As Boolean
            Return Me.IsNull(Me.tablempr00002.Mph_MPONOColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMph_MPONONull()
            Me(Me.tablempr00002.Mph_MPONOColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMph_VenNoNull() As Boolean
            Return Me.IsNull(Me.tablempr00002.Mph_VenNoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMph_VenNoNull()
            Me(Me.tablempr00002.Mph_VenNoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isvbi_vennamNull() As Boolean
            Return Me.IsNull(Me.tablempr00002.vbi_vennamColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setvbi_vennamNull()
            Me(Me.tablempr00002.vbi_vennamColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMph_ImpFtyNull() As Boolean
            Return Me.IsNull(Me.tablempr00002.Mph_ImpFtyColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMph_ImpFtyNull()
            Me(Me.tablempr00002.Mph_ImpFtyColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsGvi_VenNamNull() As Boolean
            Return Me.IsNull(Me.tablempr00002.Gvi_VenNamColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetGvi_VenNamNull()
            Me(Me.tablempr00002.Gvi_VenNamColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsGvi_EngNamNull() As Boolean
            Return Me.IsNull(Me.tablempr00002.Gvi_EngNamColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetGvi_EngNamNull()
            Me(Me.tablempr00002.Gvi_EngNamColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsGvi_VenAddrNull() As Boolean
            Return Me.IsNull(Me.tablempr00002.Gvi_VenAddrColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetGvi_VenAddrNull()
            Me(Me.tablempr00002.Gvi_VenAddrColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsGvi_EngAddrNull() As Boolean
            Return Me.IsNull(Me.tablempr00002.Gvi_EngAddrColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetGvi_EngAddrNull()
            Me(Me.tablempr00002.Gvi_EngAddrColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsGvi_Tel1Null() As Boolean
            Return Me.IsNull(Me.tablempr00002.Gvi_Tel1Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetGvi_Tel1Null()
            Me(Me.tablempr00002.Gvi_Tel1Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsGvi_Tel2Null() As Boolean
            Return Me.IsNull(Me.tablempr00002.Gvi_Tel2Column)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetGvi_Tel2Null()
            Me(Me.tablempr00002.Gvi_Tel2Column) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsGvi_FaxNull() As Boolean
            Return Me.IsNull(Me.tablempr00002.Gvi_FaxColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetGvi_FaxNull()
            Me(Me.tablempr00002.Gvi_FaxColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsGvi_TLXNull() As Boolean
            Return Me.IsNull(Me.tablempr00002.Gvi_TLXColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetGvi_TLXNull()
            Me(Me.tablempr00002.Gvi_TLXColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMph_CurrNull() As Boolean
            Return Me.IsNull(Me.tablempr00002.Mph_CurrColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMph_CurrNull()
            Me(Me.tablempr00002.Mph_CurrColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMph_ShpPlcNull() As Boolean
            Return Me.IsNull(Me.tablempr00002.Mph_ShpPlcColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMph_ShpPlcNull()
            Me(Me.tablempr00002.Mph_ShpPlcColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMph_rmkNull() As Boolean
            Return Me.IsNull(Me.tablempr00002.Mph_rmkColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMph_rmkNull()
            Me(Me.tablempr00002.Mph_rmkColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMph_VenAdrNull() As Boolean
            Return Me.IsNull(Me.tablempr00002.Mph_VenAdrColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMph_VenAdrNull()
            Me(Me.tablempr00002.Mph_VenAdrColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMph_VenSttNull() As Boolean
            Return Me.IsNull(Me.tablempr00002.Mph_VenSttColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMph_VenSttNull()
            Me(Me.tablempr00002.Mph_VenSttColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMph_VenCtyNull() As Boolean
            Return Me.IsNull(Me.tablempr00002.Mph_VenCtyColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMph_VenCtyNull()
            Me(Me.tablempr00002.Mph_VenCtyColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isysi_dscNull() As Boolean
            Return Me.IsNull(Me.tablempr00002.ysi_dscColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setysi_dscNull()
            Me(Me.tablempr00002.ysi_dscColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMph_VenPstNull() As Boolean
            Return Me.IsNull(Me.tablempr00002.Mph_VenPstColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMph_VenPstNull()
            Me(Me.tablempr00002.Mph_VenPstColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMph_MporCtpNull() As Boolean
            Return Me.IsNull(Me.tablempr00002.Mph_MporCtpColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMph_MporCtpNull()
            Me(Me.tablempr00002.Mph_MporCtpColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMph_DisCntNull() As Boolean
            Return Me.IsNull(Me.tablempr00002.Mph_DisCntColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMph_DisCntNull()
            Me(Me.tablempr00002.Mph_DisCntColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMph_ShpAdrNull() As Boolean
            Return Me.IsNull(Me.tablempr00002.Mph_ShpAdrColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMph_ShpAdrNull()
            Me(Me.tablempr00002.Mph_ShpAdrColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMph_CreDatNull() As Boolean
            Return Me.IsNull(Me.tablempr00002.Mph_CreDatColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMph_CreDatNull()
            Me(Me.tablempr00002.Mph_CreDatColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMph_UpdDatNull() As Boolean
            Return Me.IsNull(Me.tablempr00002.Mph_UpdDatColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMph_UpdDatNull()
            Me(Me.tablempr00002.Mph_UpdDatColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMpd_ItmNoNull() As Boolean
            Return Me.IsNull(Me.tablempr00002.Mpd_ItmNoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMpd_ItmNoNull()
            Me(Me.tablempr00002.Mpd_ItmNoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMpd_VenItmNull() As Boolean
            Return Me.IsNull(Me.tablempr00002.Mpd_VenItmColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMpd_VenItmNull()
            Me(Me.tablempr00002.Mpd_VenItmColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMpd_ItmNamNull() As Boolean
            Return Me.IsNull(Me.tablempr00002.Mpd_ItmNamColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMpd_ItmNamNull()
            Me(Me.tablempr00002.Mpd_ItmNamColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMpd_UMNull() As Boolean
            Return Me.IsNull(Me.tablempr00002.Mpd_UMColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMpd_UMNull()
            Me(Me.tablempr00002.Mpd_UMColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsdetailinfoNull() As Boolean
            Return Me.IsNull(Me.tablempr00002.detailinfoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetdetailinfoNull()
            Me(Me.tablempr00002.detailinfoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMPD_QTYNull() As Boolean
            Return Me.IsNull(Me.tablempr00002.MPD_QTYColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMPD_QTYNull()
            Me(Me.tablempr00002.MPD_QTYColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMpd_MinPrcNull() As Boolean
            Return Me.IsNull(Me.tablempr00002.Mpd_MinPrcColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMpd_MinPrcNull()
            Me(Me.tablempr00002.Mpd_MinPrcColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Ismpd_subamtNull() As Boolean
            Return Me.IsNull(Me.tablempr00002.mpd_subamtColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setmpd_subamtNull()
            Me(Me.tablempr00002.mpd_subamtColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsMpd_ShpDatNull() As Boolean
            Return Me.IsNull(Me.tablempr00002.Mpd_ShpDatColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetMpd_ShpDatNull()
            Me(Me.tablempr00002.Mpd_ShpDatColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsRevised_FlagNull() As Boolean
            Return Me.IsNull(Me.tablempr00002.Revised_FlagColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetRevised_FlagNull()
            Me(Me.tablempr00002.Revised_FlagColumn) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Public Class mpr00002RowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As mpr00002Row
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New(ByVal row As mpr00002Row, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Row() As mpr00002Row
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
