'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3655
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On



'''<summary>
'''Represents a strongly typed in-memory cache of data.
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
 Global.System.Serializable(),  _
 Global.System.ComponentModel.DesignerCategoryAttribute("code"),  _
 Global.System.ComponentModel.ToolboxItem(true),  _
 Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 Global.System.Xml.Serialization.XmlRootAttribute("MSR00009_container"),  _
 Global.System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class MSR00009_container
    Inherits Global.System.Data.DataSet
    
    Private tableMSR0009_container As MSR0009_containerDataTable
    
    Private _schemaSerializationMode As Global.System.Data.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("MSR0009_container")) Is Nothing) Then
                MyBase.Tables.Add(New MSR0009_containerDataTable(ds.Tables("MSR0009_container")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New Global.System.Xml.XmlTextReader(New Global.System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As Global.System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.Browsable(false),  _
     Global.System.ComponentModel.DesignerSerializationVisibility(Global.System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property MSR0009_container() As MSR0009_containerDataTable
        Get
            Return Me.tableMSR0009_container
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.BrowsableAttribute(true),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As Global.System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As Global.System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.ComponentModel.DesignerSerializationVisibilityAttribute(Global.System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As Global.System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Overrides Function Clone() As Global.System.Data.DataSet
        Dim cln As MSR00009_container = CType(MyBase.Clone,MSR00009_container)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As Global.System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = Global.System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As Global.System.Data.DataSet = New Global.System.Data.DataSet
            ds.ReadXml(reader)
            If (Not (ds.Tables("MSR0009_container")) Is Nothing) Then
                MyBase.Tables.Add(New MSR0009_containerDataTable(ds.Tables("MSR0009_container")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, Global.System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function GetSchemaSerializable() As Global.System.Xml.Schema.XmlSchema
        Dim stream As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
        Me.WriteXmlSchema(New Global.System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return Global.System.Xml.Schema.XmlSchema.Read(New Global.System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tableMSR0009_container = CType(MyBase.Tables("MSR0009_container"),MSR0009_containerDataTable)
        If (initTable = true) Then
            If (Not (Me.tableMSR0009_container) Is Nothing) Then
                Me.tableMSR0009_container.InitVars
            End If
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub InitClass()
        Me.DataSetName = "MSR00009_container"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/MSR00009_container.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = Global.System.Data.SchemaSerializationMode.IncludeSchema
        Me.tableMSR0009_container = New MSR0009_containerDataTable
        MyBase.Tables.Add(Me.tableMSR0009_container)
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Function ShouldSerializeMSR0009_container() As Boolean
        Return false
    End Function
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As Global.System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = Global.System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
        Dim ds As MSR00009_container = New MSR00009_container
        Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
        Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
        Dim any As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
        If xs.Contains(dsSchema.TargetNamespace) Then
            Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
            Try 
                Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                dsSchema.Write(s1)
                Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                Do While schemas.MoveNext
                    schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                    s2.SetLength(0)
                    schema.Write(s2)
                    If (s1.Length = s2.Length) Then
                        s1.Position = 0
                        s2.Position = 0
                        
                        Do While ((s1.Position <> s1.Length)  _
                                    AndAlso (s1.ReadByte = s2.ReadByte))
                            
                            
                        Loop
                        If (s1.Position = s1.Length) Then
                            Return type
                        End If
                    End If
                    
                Loop
            Finally
                If (Not (s1) Is Nothing) Then
                    s1.Close
                End If
                If (Not (s2) Is Nothing) Then
                    s2.Close
                End If
            End Try
        End If
        xs.Add(dsSchema)
        Return type
    End Function
    
    Public Delegate Sub MSR0009_containerRowChangeEventHandler(ByVal sender As Object, ByVal e As MSR0009_containerRowChangeEvent)
    
    '''<summary>
    '''Represents the strongly named DataTable class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
     Global.System.Serializable(),  _
     Global.System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class MSR0009_containerDataTable
        Inherits Global.System.Data.DataTable
        Implements Global.System.Collections.IEnumerable
        
        Private columnCocde As Global.System.Data.DataColumn
        
        Private columnhih_Cocde As Global.System.Data.DataColumn
        
        Private columnhih_cus1no As Global.System.Data.DataColumn
        
        Private columnpri_cbi_cussna As Global.System.Data.DataColumn
        
        Private columnhih_cus2no As Global.System.Data.DataColumn
        
        Private columnsec_cbi_cussna As Global.System.Data.DataColumn
        
        Private columnhid_invno As Global.System.Data.DataColumn
        
        Private columnhiv_invdat As Global.System.Data.DataColumn
        
        Private columnhid_shpno As Global.System.Data.DataColumn
        
        Private columnhih_ves As Global.System.Data.DataColumn
        
        Private columnhih_voy As Global.System.Data.DataColumn
        
        Private columnhih_slnonb As Global.System.Data.DataColumn
        
        Private columnhih_dst As Global.System.Data.DataColumn
        
        Private columnhiv_prctrm As Global.System.Data.DataColumn
        
        Private columnhiv_paytrm As Global.System.Data.DataColumn
        
        Private columnhiv_untamt As Global.System.Data.DataColumn
        
        Private columnhiv_invamt As Global.System.Data.DataColumn
        
        Private columnhiv_ttlamt As Global.System.Data.DataColumn
        
        Private columnhih_shpsts As Global.System.Data.DataColumn
        
        Private columnopt1Fm_InvNo As Global.System.Data.DataColumn
        
        Private columnopt1To_InvNo As Global.System.Data.DataColumn
        
        Private columnopt2Fm_CUST As Global.System.Data.DataColumn
        
        Private columnopt2To_CUST As Global.System.Data.DataColumn
        
        Private columnopt3Fm_INVDAT As Global.System.Data.DataColumn
        
        Private columnopt3To_INVDAT As Global.System.Data.DataColumn
        
        Private columnoptSortBy As Global.System.Data.DataColumn
        
        Private columnoptShpsts As Global.System.Data.DataColumn
        
        Private columnyco_conam As Global.System.Data.DataColumn
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "MSR0009_container"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal table As Global.System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Sub New(ByVal info As Global.System.Runtime.Serialization.SerializationInfo, ByVal context As Global.System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property CocdeColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnCocde
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property hih_CocdeColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnhih_Cocde
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property hih_cus1noColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnhih_cus1no
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property pri_cbi_cussnaColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnpri_cbi_cussna
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property hih_cus2noColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnhih_cus2no
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property sec_cbi_cussnaColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnsec_cbi_cussna
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property hid_invnoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnhid_invno
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property hiv_invdatColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnhiv_invdat
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property hid_shpnoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnhid_shpno
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property hih_vesColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnhih_ves
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property hih_voyColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnhih_voy
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property hih_slnonbColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnhih_slnonb
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property hih_dstColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnhih_dst
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property hiv_prctrmColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnhiv_prctrm
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property hiv_paytrmColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnhiv_paytrm
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property hiv_untamtColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnhiv_untamt
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property hiv_invamtColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnhiv_invamt
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property hiv_ttlamtColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnhiv_ttlamt
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property hih_shpstsColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnhih_shpsts
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property opt1Fm_InvNoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnopt1Fm_InvNo
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property opt1To_InvNoColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnopt1To_InvNo
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property opt2Fm_CUSTColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnopt2Fm_CUST
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property opt2To_CUSTColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnopt2To_CUST
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property opt3Fm_INVDATColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnopt3Fm_INVDAT
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property opt3To_INVDATColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnopt3To_INVDAT
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property optSortByColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnoptSortBy
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property optShpstsColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnoptShpsts
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property yco_conamColumn() As Global.System.Data.DataColumn
            Get
                Return Me.columnyco_conam
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As MSR0009_containerRow
            Get
                Return CType(Me.Rows(index),MSR0009_containerRow)
            End Get
        End Property
        
        Public Event MSR0009_containerRowChanging As MSR0009_containerRowChangeEventHandler
        
        Public Event MSR0009_containerRowChanged As MSR0009_containerRowChangeEventHandler
        
        Public Event MSR0009_containerRowDeleting As MSR0009_containerRowChangeEventHandler
        
        Public Event MSR0009_containerRowDeleted As MSR0009_containerRowChangeEventHandler
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Sub AddMSR0009_containerRow(ByVal row As MSR0009_containerRow)
            Me.Rows.Add(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Function AddMSR0009_containerRow( _
                    ByVal Cocde As String,  _
                    ByVal hih_Cocde As String,  _
                    ByVal hih_cus1no As String,  _
                    ByVal pri_cbi_cussna As String,  _
                    ByVal hih_cus2no As String,  _
                    ByVal sec_cbi_cussna As String,  _
                    ByVal hid_invno As String,  _
                    ByVal hiv_invdat As String,  _
                    ByVal hid_shpno As String,  _
                    ByVal hih_ves As String,  _
                    ByVal hih_voy As String,  _
                    ByVal hih_slnonb As String,  _
                    ByVal hih_dst As String,  _
                    ByVal hiv_prctrm As String,  _
                    ByVal hiv_paytrm As String,  _
                    ByVal hiv_untamt As String,  _
                    ByVal hiv_invamt As Integer,  _
                    ByVal hiv_ttlamt As Integer,  _
                    ByVal hih_shpsts As String,  _
                    ByVal opt1Fm_InvNo As String,  _
                    ByVal opt1To_InvNo As String,  _
                    ByVal opt2Fm_CUST As String,  _
                    ByVal opt2To_CUST As String,  _
                    ByVal opt3Fm_INVDAT As String,  _
                    ByVal opt3To_INVDAT As String,  _
                    ByVal optSortBy As String,  _
                    ByVal optShpsts As String,  _
                    ByVal yco_conam As String) As MSR0009_containerRow
            Dim rowMSR0009_containerRow As MSR0009_containerRow = CType(Me.NewRow,MSR0009_containerRow)
            Dim columnValuesArray() As Object = New Object() {Cocde, hih_Cocde, hih_cus1no, pri_cbi_cussna, hih_cus2no, sec_cbi_cussna, hid_invno, hiv_invdat, hid_shpno, hih_ves, hih_voy, hih_slnonb, hih_dst, hiv_prctrm, hiv_paytrm, hiv_untamt, hiv_invamt, hiv_ttlamt, hih_shpsts, opt1Fm_InvNo, opt1To_InvNo, opt2Fm_CUST, opt2To_CUST, opt3Fm_INVDAT, opt3To_INVDAT, optSortBy, optShpsts, yco_conam}
            rowMSR0009_containerRow.ItemArray = columnValuesArray
            Me.Rows.Add(rowMSR0009_containerRow)
            Return rowMSR0009_containerRow
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overridable Function GetEnumerator() As Global.System.Collections.IEnumerator Implements Global.System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overrides Function Clone() As Global.System.Data.DataTable
            Dim cln As MSR0009_containerDataTable = CType(MyBase.Clone,MSR0009_containerDataTable)
            cln.InitVars
            Return cln
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function CreateInstance() As Global.System.Data.DataTable
            Return New MSR0009_containerDataTable
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub InitVars()
            Me.columnCocde = MyBase.Columns("Cocde")
            Me.columnhih_Cocde = MyBase.Columns("hih_Cocde")
            Me.columnhih_cus1no = MyBase.Columns("hih_cus1no")
            Me.columnpri_cbi_cussna = MyBase.Columns("pri_cbi_cussna")
            Me.columnhih_cus2no = MyBase.Columns("hih_cus2no")
            Me.columnsec_cbi_cussna = MyBase.Columns("sec_cbi_cussna")
            Me.columnhid_invno = MyBase.Columns("hid_invno")
            Me.columnhiv_invdat = MyBase.Columns("hiv_invdat")
            Me.columnhid_shpno = MyBase.Columns("hid_shpno")
            Me.columnhih_ves = MyBase.Columns("hih_ves")
            Me.columnhih_voy = MyBase.Columns("hih_voy")
            Me.columnhih_slnonb = MyBase.Columns("hih_slnonb")
            Me.columnhih_dst = MyBase.Columns("hih_dst")
            Me.columnhiv_prctrm = MyBase.Columns("hiv_prctrm")
            Me.columnhiv_paytrm = MyBase.Columns("hiv_paytrm")
            Me.columnhiv_untamt = MyBase.Columns("hiv_untamt")
            Me.columnhiv_invamt = MyBase.Columns("hiv_invamt")
            Me.columnhiv_ttlamt = MyBase.Columns("hiv_ttlamt")
            Me.columnhih_shpsts = MyBase.Columns("hih_shpsts")
            Me.columnopt1Fm_InvNo = MyBase.Columns("opt1Fm_InvNo")
            Me.columnopt1To_InvNo = MyBase.Columns("opt1To_InvNo")
            Me.columnopt2Fm_CUST = MyBase.Columns("opt2Fm_CUST")
            Me.columnopt2To_CUST = MyBase.Columns("opt2To_CUST")
            Me.columnopt3Fm_INVDAT = MyBase.Columns("opt3Fm_INVDAT")
            Me.columnopt3To_INVDAT = MyBase.Columns("opt3To_INVDAT")
            Me.columnoptSortBy = MyBase.Columns("optSortBy")
            Me.columnoptShpsts = MyBase.Columns("optShpsts")
            Me.columnyco_conam = MyBase.Columns("yco_conam")
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitClass()
            Me.columnCocde = New Global.System.Data.DataColumn("Cocde", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnCocde)
            Me.columnhih_Cocde = New Global.System.Data.DataColumn("hih_Cocde", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnhih_Cocde)
            Me.columnhih_cus1no = New Global.System.Data.DataColumn("hih_cus1no", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnhih_cus1no)
            Me.columnpri_cbi_cussna = New Global.System.Data.DataColumn("pri_cbi_cussna", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnpri_cbi_cussna)
            Me.columnhih_cus2no = New Global.System.Data.DataColumn("hih_cus2no", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnhih_cus2no)
            Me.columnsec_cbi_cussna = New Global.System.Data.DataColumn("sec_cbi_cussna", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnsec_cbi_cussna)
            Me.columnhid_invno = New Global.System.Data.DataColumn("hid_invno", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnhid_invno)
            Me.columnhiv_invdat = New Global.System.Data.DataColumn("hiv_invdat", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnhiv_invdat)
            Me.columnhid_shpno = New Global.System.Data.DataColumn("hid_shpno", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnhid_shpno)
            Me.columnhih_ves = New Global.System.Data.DataColumn("hih_ves", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnhih_ves)
            Me.columnhih_voy = New Global.System.Data.DataColumn("hih_voy", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnhih_voy)
            Me.columnhih_slnonb = New Global.System.Data.DataColumn("hih_slnonb", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnhih_slnonb)
            Me.columnhih_dst = New Global.System.Data.DataColumn("hih_dst", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnhih_dst)
            Me.columnhiv_prctrm = New Global.System.Data.DataColumn("hiv_prctrm", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnhiv_prctrm)
            Me.columnhiv_paytrm = New Global.System.Data.DataColumn("hiv_paytrm", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnhiv_paytrm)
            Me.columnhiv_untamt = New Global.System.Data.DataColumn("hiv_untamt", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnhiv_untamt)
            Me.columnhiv_invamt = New Global.System.Data.DataColumn("hiv_invamt", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnhiv_invamt)
            Me.columnhiv_ttlamt = New Global.System.Data.DataColumn("hiv_ttlamt", GetType(Integer), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnhiv_ttlamt)
            Me.columnhih_shpsts = New Global.System.Data.DataColumn("hih_shpsts", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnhih_shpsts)
            Me.columnopt1Fm_InvNo = New Global.System.Data.DataColumn("opt1Fm_InvNo", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnopt1Fm_InvNo)
            Me.columnopt1To_InvNo = New Global.System.Data.DataColumn("opt1To_InvNo", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnopt1To_InvNo)
            Me.columnopt2Fm_CUST = New Global.System.Data.DataColumn("opt2Fm_CUST", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnopt2Fm_CUST)
            Me.columnopt2To_CUST = New Global.System.Data.DataColumn("opt2To_CUST", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnopt2To_CUST)
            Me.columnopt3Fm_INVDAT = New Global.System.Data.DataColumn("opt3Fm_INVDAT", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnopt3Fm_INVDAT)
            Me.columnopt3To_INVDAT = New Global.System.Data.DataColumn("opt3To_INVDAT", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnopt3To_INVDAT)
            Me.columnoptSortBy = New Global.System.Data.DataColumn("optSortBy", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnoptSortBy)
            Me.columnoptShpsts = New Global.System.Data.DataColumn("optShpsts", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnoptShpsts)
            Me.columnyco_conam = New Global.System.Data.DataColumn("yco_conam", GetType(String), Nothing, Global.System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnyco_conam)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function NewMSR0009_containerRow() As MSR0009_containerRow
            Return CType(Me.NewRow,MSR0009_containerRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As Global.System.Data.DataRowBuilder) As Global.System.Data.DataRow
            Return New MSR0009_containerRow(builder)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function GetRowType() As Global.System.Type
            Return GetType(MSR0009_containerRow)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanged(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.MSR0009_containerRowChangedEvent) Is Nothing) Then
                RaiseEvent MSR0009_containerRowChanged(Me, New MSR0009_containerRowChangeEvent(CType(e.Row,MSR0009_containerRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanging(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.MSR0009_containerRowChangingEvent) Is Nothing) Then
                RaiseEvent MSR0009_containerRowChanging(Me, New MSR0009_containerRowChangeEvent(CType(e.Row,MSR0009_containerRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.MSR0009_containerRowDeletedEvent) Is Nothing) Then
                RaiseEvent MSR0009_containerRowDeleted(Me, New MSR0009_containerRowChangeEvent(CType(e.Row,MSR0009_containerRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As Global.System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.MSR0009_containerRowDeletingEvent) Is Nothing) Then
                RaiseEvent MSR0009_containerRowDeleting(Me, New MSR0009_containerRowChangeEvent(CType(e.Row,MSR0009_containerRow), e.Action))
            End If
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub RemoveMSR0009_containerRow(ByVal row As MSR0009_containerRow)
            Me.Rows.Remove(row)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As Global.System.Xml.Schema.XmlSchemaSet) As Global.System.Xml.Schema.XmlSchemaComplexType
            Dim type As Global.System.Xml.Schema.XmlSchemaComplexType = New Global.System.Xml.Schema.XmlSchemaComplexType
            Dim sequence As Global.System.Xml.Schema.XmlSchemaSequence = New Global.System.Xml.Schema.XmlSchemaSequence
            Dim ds As MSR00009_container = New MSR00009_container
            Dim any1 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As Global.System.Xml.Schema.XmlSchemaAny = New Global.System.Xml.Schema.XmlSchemaAny
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = Global.System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As Global.System.Xml.Schema.XmlSchemaAttribute = New Global.System.Xml.Schema.XmlSchemaAttribute
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "MSR0009_containerDataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Dim dsSchema As Global.System.Xml.Schema.XmlSchema = ds.GetSchemaSerializable
            If xs.Contains(dsSchema.TargetNamespace) Then
                Dim s1 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Dim s2 As Global.System.IO.MemoryStream = New Global.System.IO.MemoryStream
                Try 
                    Dim schema As Global.System.Xml.Schema.XmlSchema = Nothing
                    dsSchema.Write(s1)
                    Dim schemas As Global.System.Collections.IEnumerator = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator
                    Do While schemas.MoveNext
                        schema = CType(schemas.Current,Global.System.Xml.Schema.XmlSchema)
                        s2.SetLength(0)
                        schema.Write(s2)
                        If (s1.Length = s2.Length) Then
                            s1.Position = 0
                            s2.Position = 0
                            
                            Do While ((s1.Position <> s1.Length)  _
                                        AndAlso (s1.ReadByte = s2.ReadByte))
                                
                                
                            Loop
                            If (s1.Position = s1.Length) Then
                                Return type
                            End If
                        End If
                        
                    Loop
                Finally
                    If (Not (s1) Is Nothing) Then
                        s1.Close
                    End If
                    If (Not (s2) Is Nothing) Then
                        s2.Close
                    End If
                End Try
            End If
            xs.Add(dsSchema)
            Return type
        End Function
    End Class
    
    '''<summary>
    '''Represents strongly named DataRow class.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Partial Public Class MSR0009_containerRow
        Inherits Global.System.Data.DataRow
        
        Private tableMSR0009_container As MSR0009_containerDataTable
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal rb As Global.System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tableMSR0009_container = CType(Me.Table,MSR0009_containerDataTable)
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property Cocde() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR0009_container.CocdeColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'Cocde' in table 'MSR0009_container' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR0009_container.CocdeColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property hih_Cocde() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR0009_container.hih_CocdeColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'hih_Cocde' in table 'MSR0009_container' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR0009_container.hih_CocdeColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property hih_cus1no() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR0009_container.hih_cus1noColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'hih_cus1no' in table 'MSR0009_container' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR0009_container.hih_cus1noColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property pri_cbi_cussna() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR0009_container.pri_cbi_cussnaColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'pri_cbi_cussna' in table 'MSR0009_container' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR0009_container.pri_cbi_cussnaColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property hih_cus2no() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR0009_container.hih_cus2noColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'hih_cus2no' in table 'MSR0009_container' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR0009_container.hih_cus2noColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property sec_cbi_cussna() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR0009_container.sec_cbi_cussnaColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'sec_cbi_cussna' in table 'MSR0009_container' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR0009_container.sec_cbi_cussnaColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property hid_invno() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR0009_container.hid_invnoColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'hid_invno' in table 'MSR0009_container' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR0009_container.hid_invnoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property hiv_invdat() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR0009_container.hiv_invdatColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'hiv_invdat' in table 'MSR0009_container' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR0009_container.hiv_invdatColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property hid_shpno() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR0009_container.hid_shpnoColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'hid_shpno' in table 'MSR0009_container' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR0009_container.hid_shpnoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property hih_ves() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR0009_container.hih_vesColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'hih_ves' in table 'MSR0009_container' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR0009_container.hih_vesColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property hih_voy() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR0009_container.hih_voyColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'hih_voy' in table 'MSR0009_container' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR0009_container.hih_voyColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property hih_slnonb() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR0009_container.hih_slnonbColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'hih_slnonb' in table 'MSR0009_container' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR0009_container.hih_slnonbColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property hih_dst() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR0009_container.hih_dstColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'hih_dst' in table 'MSR0009_container' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR0009_container.hih_dstColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property hiv_prctrm() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR0009_container.hiv_prctrmColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'hiv_prctrm' in table 'MSR0009_container' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR0009_container.hiv_prctrmColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property hiv_paytrm() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR0009_container.hiv_paytrmColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'hiv_paytrm' in table 'MSR0009_container' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR0009_container.hiv_paytrmColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property hiv_untamt() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR0009_container.hiv_untamtColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'hiv_untamt' in table 'MSR0009_container' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR0009_container.hiv_untamtColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property hiv_invamt() As Integer
            Get
                Try 
                    Return CType(Me(Me.tableMSR0009_container.hiv_invamtColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'hiv_invamt' in table 'MSR0009_container' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR0009_container.hiv_invamtColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property hiv_ttlamt() As Integer
            Get
                Try 
                    Return CType(Me(Me.tableMSR0009_container.hiv_ttlamtColumn),Integer)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'hiv_ttlamt' in table 'MSR0009_container' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR0009_container.hiv_ttlamtColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property hih_shpsts() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR0009_container.hih_shpstsColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'hih_shpsts' in table 'MSR0009_container' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR0009_container.hih_shpstsColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property opt1Fm_InvNo() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR0009_container.opt1Fm_InvNoColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'opt1Fm_InvNo' in table 'MSR0009_container' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR0009_container.opt1Fm_InvNoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property opt1To_InvNo() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR0009_container.opt1To_InvNoColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'opt1To_InvNo' in table 'MSR0009_container' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR0009_container.opt1To_InvNoColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property opt2Fm_CUST() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR0009_container.opt2Fm_CUSTColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'opt2Fm_CUST' in table 'MSR0009_container' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR0009_container.opt2Fm_CUSTColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property opt2To_CUST() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR0009_container.opt2To_CUSTColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'opt2To_CUST' in table 'MSR0009_container' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR0009_container.opt2To_CUSTColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property opt3Fm_INVDAT() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR0009_container.opt3Fm_INVDATColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'opt3Fm_INVDAT' in table 'MSR0009_container' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR0009_container.opt3Fm_INVDATColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property opt3To_INVDAT() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR0009_container.opt3To_INVDATColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'opt3To_INVDAT' in table 'MSR0009_container' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR0009_container.opt3To_INVDATColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property optSortBy() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR0009_container.optSortByColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'optSortBy' in table 'MSR0009_container' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR0009_container.optSortByColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property optShpsts() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR0009_container.optShpstsColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'optShpsts' in table 'MSR0009_container' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR0009_container.optShpstsColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property yco_conam() As String
            Get
                Try 
                    Return CType(Me(Me.tableMSR0009_container.yco_conamColumn),String)
                Catch e As Global.System.InvalidCastException
                    Throw New Global.System.Data.StrongTypingException("The value for column 'yco_conam' in table 'MSR0009_container' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableMSR0009_container.yco_conamColumn) = value
            End Set
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsCocdeNull() As Boolean
            Return Me.IsNull(Me.tableMSR0009_container.CocdeColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetCocdeNull()
            Me(Me.tableMSR0009_container.CocdeColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Ishih_CocdeNull() As Boolean
            Return Me.IsNull(Me.tableMSR0009_container.hih_CocdeColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Sethih_CocdeNull()
            Me(Me.tableMSR0009_container.hih_CocdeColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Ishih_cus1noNull() As Boolean
            Return Me.IsNull(Me.tableMSR0009_container.hih_cus1noColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Sethih_cus1noNull()
            Me(Me.tableMSR0009_container.hih_cus1noColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Ispri_cbi_cussnaNull() As Boolean
            Return Me.IsNull(Me.tableMSR0009_container.pri_cbi_cussnaColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setpri_cbi_cussnaNull()
            Me(Me.tableMSR0009_container.pri_cbi_cussnaColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Ishih_cus2noNull() As Boolean
            Return Me.IsNull(Me.tableMSR0009_container.hih_cus2noColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Sethih_cus2noNull()
            Me(Me.tableMSR0009_container.hih_cus2noColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Issec_cbi_cussnaNull() As Boolean
            Return Me.IsNull(Me.tableMSR0009_container.sec_cbi_cussnaColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setsec_cbi_cussnaNull()
            Me(Me.tableMSR0009_container.sec_cbi_cussnaColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Ishid_invnoNull() As Boolean
            Return Me.IsNull(Me.tableMSR0009_container.hid_invnoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Sethid_invnoNull()
            Me(Me.tableMSR0009_container.hid_invnoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Ishiv_invdatNull() As Boolean
            Return Me.IsNull(Me.tableMSR0009_container.hiv_invdatColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Sethiv_invdatNull()
            Me(Me.tableMSR0009_container.hiv_invdatColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Ishid_shpnoNull() As Boolean
            Return Me.IsNull(Me.tableMSR0009_container.hid_shpnoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Sethid_shpnoNull()
            Me(Me.tableMSR0009_container.hid_shpnoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Ishih_vesNull() As Boolean
            Return Me.IsNull(Me.tableMSR0009_container.hih_vesColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Sethih_vesNull()
            Me(Me.tableMSR0009_container.hih_vesColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Ishih_voyNull() As Boolean
            Return Me.IsNull(Me.tableMSR0009_container.hih_voyColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Sethih_voyNull()
            Me(Me.tableMSR0009_container.hih_voyColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Ishih_slnonbNull() As Boolean
            Return Me.IsNull(Me.tableMSR0009_container.hih_slnonbColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Sethih_slnonbNull()
            Me(Me.tableMSR0009_container.hih_slnonbColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Ishih_dstNull() As Boolean
            Return Me.IsNull(Me.tableMSR0009_container.hih_dstColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Sethih_dstNull()
            Me(Me.tableMSR0009_container.hih_dstColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Ishiv_prctrmNull() As Boolean
            Return Me.IsNull(Me.tableMSR0009_container.hiv_prctrmColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Sethiv_prctrmNull()
            Me(Me.tableMSR0009_container.hiv_prctrmColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Ishiv_paytrmNull() As Boolean
            Return Me.IsNull(Me.tableMSR0009_container.hiv_paytrmColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Sethiv_paytrmNull()
            Me(Me.tableMSR0009_container.hiv_paytrmColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Ishiv_untamtNull() As Boolean
            Return Me.IsNull(Me.tableMSR0009_container.hiv_untamtColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Sethiv_untamtNull()
            Me(Me.tableMSR0009_container.hiv_untamtColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Ishiv_invamtNull() As Boolean
            Return Me.IsNull(Me.tableMSR0009_container.hiv_invamtColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Sethiv_invamtNull()
            Me(Me.tableMSR0009_container.hiv_invamtColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Ishiv_ttlamtNull() As Boolean
            Return Me.IsNull(Me.tableMSR0009_container.hiv_ttlamtColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Sethiv_ttlamtNull()
            Me(Me.tableMSR0009_container.hiv_ttlamtColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Ishih_shpstsNull() As Boolean
            Return Me.IsNull(Me.tableMSR0009_container.hih_shpstsColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Sethih_shpstsNull()
            Me(Me.tableMSR0009_container.hih_shpstsColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isopt1Fm_InvNoNull() As Boolean
            Return Me.IsNull(Me.tableMSR0009_container.opt1Fm_InvNoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setopt1Fm_InvNoNull()
            Me(Me.tableMSR0009_container.opt1Fm_InvNoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isopt1To_InvNoNull() As Boolean
            Return Me.IsNull(Me.tableMSR0009_container.opt1To_InvNoColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setopt1To_InvNoNull()
            Me(Me.tableMSR0009_container.opt1To_InvNoColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isopt2Fm_CUSTNull() As Boolean
            Return Me.IsNull(Me.tableMSR0009_container.opt2Fm_CUSTColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setopt2Fm_CUSTNull()
            Me(Me.tableMSR0009_container.opt2Fm_CUSTColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isopt2To_CUSTNull() As Boolean
            Return Me.IsNull(Me.tableMSR0009_container.opt2To_CUSTColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setopt2To_CUSTNull()
            Me(Me.tableMSR0009_container.opt2To_CUSTColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isopt3Fm_INVDATNull() As Boolean
            Return Me.IsNull(Me.tableMSR0009_container.opt3Fm_INVDATColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setopt3Fm_INVDATNull()
            Me(Me.tableMSR0009_container.opt3Fm_INVDATColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isopt3To_INVDATNull() As Boolean
            Return Me.IsNull(Me.tableMSR0009_container.opt3To_INVDATColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setopt3To_INVDATNull()
            Me(Me.tableMSR0009_container.opt3To_INVDATColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsoptSortByNull() As Boolean
            Return Me.IsNull(Me.tableMSR0009_container.optSortByColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetoptSortByNull()
            Me(Me.tableMSR0009_container.optSortByColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function IsoptShpstsNull() As Boolean
            Return Me.IsNull(Me.tableMSR0009_container.optShpstsColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub SetoptShpstsNull()
            Me(Me.tableMSR0009_container.optShpstsColumn) = Global.System.Convert.DBNull
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isyco_conamNull() As Boolean
            Return Me.IsNull(Me.tableMSR0009_container.yco_conamColumn)
        End Function
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setyco_conamNull()
            Me(Me.tableMSR0009_container.yco_conamColumn) = Global.System.Convert.DBNull
        End Sub
    End Class
    
    '''<summary>
    '''Row event argument class
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Public Class MSR0009_containerRowChangeEvent
        Inherits Global.System.EventArgs
        
        Private eventRow As MSR0009_containerRow
        
        Private eventAction As Global.System.Data.DataRowAction
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New(ByVal row As MSR0009_containerRow, ByVal action As Global.System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Row() As MSR0009_containerRow
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Action() As Global.System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
